project_id = "kukukejlhwcwfsdeyibd"

[functions.process-audio]
enabled = true
verify_jwt = false
import_map = "./functions/process-audio/deno.json"
entrypoint = "./functions/process-audio/index.ts"

[functions.generate-survey-draft]
enabled = true
verify_jwt = true
entrypoint = "./functions/generate-survey-draft/index.ts"