import { Sparkles } from "lucide-react";
import { Badge } from "../ui/Badge";
import { Button } from "../ui/button";
import { Card } from "../ui/Card";
import { Chip } from "../ui/Chip";
import { SkeletonBlock } from "../ui/SkeletonBlock";

type AISummaryPanelProps = {
  loading: boolean;
  onRegenerate: () => void;
};

const recommendations = [
  "Review pricing communication",
  "Highlight delivery speed in marketing",
  "Follow up on 9 negative responses",
];

export function AISummaryPanel({ loading, onRegenerate }: AISummaryPanelProps) {
  return (
    <Card className="border-l-2 border-l-accent-500 bg-accent-50">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Badge variant="draft" className="text-accent-700">
            <Sparkles className="h-3 w-3" />
            AI summary
          </Badge>
          <span className="text-xs text-gray-400">Generated just now</span>
        </div>
        <Button variant="ghost" size="sm" onClick={onRegenerate}>Regenerate</Button>
      </div>
      {loading ? (
        <div className="mt-5 space-y-3">
          <SkeletonBlock className="h-5" />
          <SkeletonBlock className="h-5 w-11/12" />
          <SkeletonBlock className="h-5 w-4/5" />
          <div className="flex flex-wrap gap-2 pt-3">
            <SkeletonBlock className="h-7 w-40 rounded-full" />
            <SkeletonBlock className="h-7 w-48 rounded-full" />
            <SkeletonBlock className="h-7 w-52 rounded-full" />
          </div>
        </div>
      ) : (
        <div className="mt-5 motion-safe:animate-[fade-in_200ms_ease]">
          <div className="max-w-5xl space-y-4 text-md leading-7 text-gray-700">
            <p>
              Respondents overwhelmingly highlighted fast delivery and friendly support as standout positives. The most recurring concern was around pricing transparency, mentioned in 34% of responses.
            </p>
            <p>
              Overall sentiment is strongly positive at 78%, up 12 points from the previous survey period. The strongest opportunity is to clarify renewal pricing before invoice conversations begin.
            </p>
          </div>
          <div className="mt-5 flex flex-wrap gap-2">
            {recommendations.map((item) => (
              <Chip key={item} active className="border-accent-400 bg-accent-100 text-accent-700">
                {item}
              </Chip>
            ))}
          </div>
          <p className="mt-4 text-xs text-gray-400">Generated by AI - just now</p>
        </div>
      )}
    </Card>
  );
}
